export const API_ENDPOINTS = {
  authLogin: "/api/auth/login",
  authRegister: "/api/auth/register",
  authLogout: "/api/auth/logout",
  authMe: "/api/auth/me",
  recruiterCandidates: "/api/recruiter/candidates",
  recruiterUnlock: "/api/recruiter/unlock",
  recruiterWallet: "/api/recruiter/wallet",
  recruiterTopup: "/api/recruiter/topup",
  reviews: "/api/reviews",
  referrals: "/api/referrals",
  referralApply: (referralId: string) => `/api/referrals/${referralId}/apply`,
  salaries: "/api/salaries",
  bankerMyReferrals: "/api/banker/referrals/mine",
  bankerReferralApplicants: (referralId: string) => `/api/banker/referrals/${referralId}/applicants`,
  adminDashboard: "/api/admin/dashboard",
  adminBootstrap: "/api/admin/bootstrap",
  adminContent: "/api/admin/content",
  adminContentPublish: "/api/admin/content/publish",
  adminUsers: "/api/admin/users",
  adminUserById: (userId: string) => `/api/admin/users/${userId}`,
  adminBulkSuspend: "/api/admin/users/bulk/suspend",
  adminBulkEmail: "/api/admin/users/bulk/email",
  adminJobs: "/api/admin/jobs",
  adminJobById: (jobId: string) => `/api/admin/jobs/${jobId}`,
  adminReferrals: "/api/admin/referrals",
  adminReferralStatus: (id: string) => `/api/admin/referrals/${id}/status`,
  adminAnalytics: "/api/admin/analytics",
  adminAnalyticsExport: (type: string) => `/api/admin/analytics/export?type=${encodeURIComponent(type)}`,
  adminSettings: "/api/admin/settings",
  adminRotateApiKey: (environment: "production" | "test") =>
    `/api/admin/settings/api-keys/${environment}/rotate`,
  adminEmailTest: "/api/admin/settings/email/test",
  adminWebhookTest: "/api/admin/settings/webhooks/test",
} as const
