export const COLLECTIONS = {
  users: "users",
  candidateProfiles: "candidate_profiles",
  candidateUnlockEvents: "candidate_unlock_events",
  creditLedger: "credit_ledger",
  cultureReviews: "culture_reviews",
  referrals: "referrals",
  referralApplications: "referral_applications",
  salaryIntel: "salary_intel",
  jobPosts: "job_posts",
  adminContent: "admin_content",
  adminSettings: "admin_settings",
  adminAuditLogs: "admin_audit_logs",
  adminApiKeys: "admin_api_keys",
  adminWebhookEvents: "admin_webhook_events",
} as const
